start on started lab126
stop on stopping lab126

script
  sleep 15
  /mnt/us/extensions/tailscale/bin/start_tailscaled_tun.sh
  sleep 3
  /mnt/us/extensions/tailscale/bin/start_tailscale.sh
end script
