-- ./settings/bookends.lua
return {
    ["active_preset_filename"] = "essentially_minimal.lua",
    ["bar_colors_promoted_to_per_bar"] = true,
    ["bottom_center_tap_action"] = "toggle",
    ["check_updates"] = true,
    ["detached_state_recovery_done"] = true,
    ["dev_branch"] = "",
    ["enabled"] = true,
    ["font_face"] = "NotoSans-Regular.ttf",
    ["font_scale"] = 100,
    ["font_size"] = 14,
    ["last_install_source"] = "release",
    ["margin_bottom"] = 50,
    ["margin_left"] = 18,
    ["margin_right"] = 18,
    ["margin_top"] = 10,
    ["migrated"] = true,
    ["overlap_gap"] = 50,
    ["pages_left_includes_current"] = false,
    ["pos_bc"] = {
        ["line_bar_height"] = {},
        ["line_bar_style"] = {
            [2] = "rounded",
        },
        ["line_bar_type"] = {},
        ["line_font_face"] = {},
        ["line_font_size"] = {
            [1] = 14,
            [2] = 10,
        },
        ["line_h_nudge"] = {},
        ["line_page_filter"] = {},
        ["line_style"] = {},
        ["line_uppercase"] = {},
        ["line_v_nudge"] = {
            [1] = 70,
            [2] = 55,
        },
        ["lines"] = {
            [1] = "%page_num of %page_count",
            [2] = "%bar",
        },
    },
    ["pos_bl"] = {
        ["line_bar_height"] = {},
        ["line_bar_style"] = {},
        ["line_bar_type"] = {},
        ["line_font_face"] = {},
        ["line_font_size"] = {
            [1] = 14,
        },
        ["line_h_nudge"] = {},
        ["line_page_filter"] = {},
        ["line_style"] = {},
        ["line_uppercase"] = {},
        ["line_v_nudge"] = {
            [1] = 55,
        },
        ["lines"] = {
            [1] = "⏳ %chap_time_left • %book_pct",
        },
    },
    ["pos_br"] = {
        ["line_bar_height"] = {},
        ["line_bar_style"] = {},
        ["line_bar_type"] = {},
        ["line_font_face"] = {},
        ["line_font_size"] = {},
        ["line_h_nudge"] = {},
        ["line_page_filter"] = {},
        ["line_style"] = {},
        ["line_uppercase"] = {},
        ["line_v_nudge"] = {
            [1] = 55,
        },
        ["lines"] = {
            [1] = "%batt_icon%batt • %wifi",
        },
    },
    ["pos_tc"] = {
        ["disabled"] = true,
        ["line_bar_height"] = {},
        ["line_bar_style"] = {},
        ["line_bar_type"] = {},
        ["line_font_face"] = {},
        ["line_font_size"] = {
            [1] = 14,
        },
        ["line_h_nudge"] = {},
        ["line_page_filter"] = {},
        ["line_style"] = {
            [1] = "bold",
        },
        ["line_uppercase"] = {},
        ["line_v_nudge"] = {
            [1] = -10,
        },
        ["lines"] = {
            [1] = "%time_24h",
        },
    },
    ["pos_tl"] = {
        ["disabled"] = true,
        ["line_bar_height"] = {},
        ["line_bar_style"] = {},
        ["line_bar_type"] = {},
        ["line_font_face"] = {},
        ["line_font_size"] = {
            [1] = 12,
            [2] = 12,
        },
        ["line_h_nudge"] = {},
        ["line_page_filter"] = {},
        ["line_style"] = {},
        ["line_uppercase"] = {},
        ["line_v_nudge"] = {
            [1] = -10,
            [2] = -25,
        },
        ["lines"] = {
            [1] = "%title",
            [2] = "%series",
        },
    },
    ["pos_tr"] = {
        ["disabled"] = true,
        ["line_bar_height"] = {},
        ["line_bar_style"] = {},
        ["line_bar_type"] = {},
        ["line_font_face"] = {},
        ["line_font_size"] = {
            [1] = 12,
        },
        ["line_h_nudge"] = {},
        ["line_page_filter"] = {},
        ["line_style"] = {},
        ["line_uppercase"] = {},
        ["line_v_nudge"] = {
            [1] = -10,
        },
        ["lines"] = {
            [1] = "%chap_title",
        },
    },
    ["preset_cycle"] = {
        [1] = "basic_bookends.lua",
    },
    ["preset_manager_migration_done"] = true,
    ["progress_bar_1"] = {
        ["chapter_ticks"] = "all",
        ["enabled"] = false,
        ["height"] = 20,
        ["margin_left"] = 0,
        ["margin_right"] = 0,
        ["margin_v"] = 0,
        ["style"] = "solid",
        ["type"] = "book",
        ["v_anchor"] = "bottom",
    },
    ["progress_bar_2"] = {
        ["chapter_ticks"] = "off",
        ["enabled"] = false,
        ["height"] = 20,
        ["margin_left"] = 0,
        ["margin_right"] = 0,
        ["margin_v"] = 0,
        ["style"] = "solid",
        ["type"] = "chapter",
        ["v_anchor"] = "bottom",
    },
    ["progress_bar_3"] = {
        ["chapter_ticks"] = "off",
        ["enabled"] = false,
        ["height"] = 20,
        ["margin_left"] = 0,
        ["margin_right"] = 0,
        ["margin_v"] = 0,
        ["style"] = "solid",
        ["type"] = "book",
        ["v_anchor"] = "bottom",
    },
    ["progress_bar_4"] = {
        ["chapter_ticks"] = "off",
        ["enabled"] = false,
        ["height"] = 20,
        ["margin_left"] = 0,
        ["margin_right"] = 0,
        ["margin_v"] = 0,
        ["style"] = "solid",
        ["type"] = "book",
        ["v_anchor"] = "bottom",
    },
    ["progress_bar_5"] = {
        ["chapter_ticks"] = "off",
        ["enabled"] = false,
        ["height"] = 20,
        ["margin_left"] = 0,
        ["margin_right"] = 0,
        ["margin_v"] = 0,
        ["style"] = "solid",
        ["type"] = "book",
        ["v_anchor"] = "bottom",
    },
    ["progress_bar_6"] = {
        ["chapter_ticks"] = "off",
        ["enabled"] = false,
        ["height"] = 20,
        ["margin_left"] = 0,
        ["margin_right"] = 0,
        ["margin_v"] = 0,
        ["style"] = "solid",
        ["type"] = "book",
        ["v_anchor"] = "bottom",
    },
    ["progress_bar_7"] = {
        ["chapter_ticks"] = "off",
        ["enabled"] = false,
        ["height"] = 20,
        ["margin_left"] = 0,
        ["margin_right"] = 0,
        ["margin_v"] = 0,
        ["style"] = "solid",
        ["type"] = "book",
        ["v_anchor"] = "bottom",
    },
    ["progress_bar_8"] = {
        ["chapter_ticks"] = "off",
        ["enabled"] = false,
        ["height"] = 20,
        ["margin_left"] = 0,
        ["margin_right"] = 0,
        ["margin_v"] = 0,
        ["style"] = "solid",
        ["type"] = "book",
        ["v_anchor"] = "bottom",
    },
    ["schema_version"] = 5,
    ["skim_on_hold"] = true,
    ["stock_bar_disabled"] = true,
    ["truncation_priority"] = "center",
}
